config/routes.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++


OpenProject::Application.routes.draw do
  root :to => 'welcome#index', :as => 'home'

  rails_relative_url_root = OpenProject::Configuration['rails_relative_url_root'] || ''

  # Redirect deprecated issue links to new work packages uris
  match '/issues(/)'    => redirect("#{rails_relative_url_root}/work_packages/")
  # The URI.escape doesn't escape / unless you ask it to.
  # see https://github.com/rails/rails/issues/5688
  match '/issues/*rest' => redirect { |params, req| "#{rails_relative_url_root}/work_packages/#{URI.escape(params[:rest])}" }

  # Redirect wp short url for work packages to full URL
  match '/wp(/)'    => redirect("#{rails_relative_url_root}/work_packages/")
  match '/wp/*rest' => redirect { |params, req| "#{rails_relative_url_root}/work_packages/#{URI.escape(params[:rest])}" }

  scope :controller => 'account' do
    get '/account/force_password_change', :action => 'force_password_change'
    post '/account/change_password', :action => 'change_password'
    get '/account/lost_password', :action => 'lost_password'

    # omniauth routes
    match '/auth/:provider/callback', :action => 'omniauth_login',
                                     :as => 'omniauth_login',
                                     :via => [:get, :post]
    get '/auth/failure', action: 'omniauth_failure'

    match '/login', :action => 'login',  :as => 'signin', :via => [:get, :post]
    get '/logout', :action => 'logout', :as => 'signout'
  end

  namespace :api do

    namespace :v2 do

      resources :authentication
      resources :users, only: [:index]
      resources :planning_element_journals
      resources :statuses
      resources :colors, :controller => 'planning_element_type_colors'
      resources :planning_element_types
      resources :planning_elements
      resources :project_types
      resources :reported_project_statuses
      resources :statuses, :only => [:index, :show]
      resources :timelines
      resources :planning_element_priorities, only: [:index]

      resources :projects do
        resources :planning_elements
        resources :planning_element_types
        resources :reportings do
          get :available_projects, :on => :collection
        end
        resources :project_associations do
          get :available_projects, :on => :collection
        end
        resources :statuses, :only => [:index, :show]
        resources :users, only: [:index]

        member do
          get :planning_element_custom_fields
        end
        resources :workflows, only: [:index]

        collection do
          get :level_list
        end
      end

      resources :custom_fields

      namespace :pagination, :as => 'paginate' do
        [:users,
         :principals,
         :statuses,
         :types,
         :project_types,
         :reported_project_statuses,
         :projects].each do |model|
          resources model, :only => [:index]
        end
      end

    end

    namespace :v3 do
      resources :work_packages, only: [:index] do
        get :column_data, on: :collection
        get :column_sums, on: :collection
      end
      resources :queries, only: [:show] do
        get :available_columns, on: :collection
        get :custom_field_filters, on: :collection
      end

      resources :projects, only: [:show, :index] do
        resources :work_packages, only: [:index] do
          get :column_sums, on: :collection
        end
        resources :queries, only: [:show] do
          get :available_columns, on: :collection
          get :custom_field_filters, on: :collection
        end
        resources :versions, only: [:index]
        get :sub_projects
        resources :users, only: [:index]
      end

      resources :groups, only: [:index]
      resources :roles, only: [:index]
      resources :users, only: [:index]
    end
  end

  match '/roles/workflow/:id/:role_id/:type_id' => 'roles#workflow'
  match '/help/:ctrl/:page' => 'help#index'

  resources :types
  resources :statuses, :except => :show do
    collection do
      post 'update_work_package_done_ratio'
    end
  end
  resources :custom_fields, :except => :show
  match "(projects/:project_id)/search" => 'search#index', :as => "search"

  # only providing routes for journals when there are multiple subclasses of journals
  # all subclasses will look for the journals routes
  resources :journals, :only => [:edit, :update] do
    get :preview, on: :member
  end

  # REVIEW: review those wiki routes
  scope "projects/:project_id/wiki/:id" do
    resource :wiki_menu_item, :only => [:edit, :update]
  end

  scope "projects/:project_id/query/:query_id" do
    resources :query_menu_items, :except => [:show]
  end

  get   'projects/:project_id/wiki/new' => 'wiki#new', :as => 'wiki_new'
  post  'projects/:project_id/wiki/new' => 'wiki#create', :as => 'wiki_create'
  get   'projects/:project_id/wiki/:id/new' => 'wiki#new_child', :as => 'wiki_new_child'
  get   'projects/:project_id/wiki/:id/toc' => 'wiki#index', :as => 'wiki_page_toc'
  post  'projects/:project_id/wiki/preview' => 'wiki#preview', as: 'preview_wiki'
  post  'projects/:id/wiki' => 'wikis#edit'
  match 'projects/:id/wiki/destroy' => 'wikis#destroy'

  # generic route for adding/removing watchers.
  # Models declared as acts_as_watchable will be automatically added to
  # OpenProject::Acts::Watchable::Routes.watched
  scope ':object_type/:object_id', :constraints => OpenProject::Acts::Watchable::Routes do
    resources :watchers, :only => [:new, :create]

    match '/watch' => 'watchers#watch', :via => :post
    match '/unwatch' => 'watchers#unwatch', :via => :delete
  end

  resources :watchers, :only => [:destroy]

  # TODO: remove
  scope "issues" do
    match 'changes' => 'journals#index', :as => 'changes'
  end

  resources :projects, :except => [:edit] do
    member do
      # this route let's you access the project specific settings (by tab)
      #
      #   settings_project_path(@project)
      #     => "/projects/1/settings"
      #
      #   settings_project_path(@project, :tab => 'members')
      #     => "/projects/1/settings/members"
      #
      get 'settings(/:tab)', :action => 'settings', :as => :settings

      match "copy_project_from_(:coming_from)" => "copy_projects#copy_project", :via => :get, :as => :copy_from,
            constraints: { coming_from: /(admin|settings)/ }
      match "copy" => "copy_projects#copy", :via => :post
      put :modules
      put :archive
      put :unarchive

      get 'column_sums', :controller => 'work_packages'

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info, :as => 'confirm_destroy'
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    resources :versions, :only => [:new, :create] do
      collection do
        put :close_completed
      end
    end

    # this is only another name for versions#index
    # For nice "road in the url for the index action
    # this could probably be rewritten with a resource :as => 'roadmap'
    match '/roadmap' => 'versions#index', :via => :get

    resources :news, :only => [:index, :new, :create]

    namespace :time_entries do
      resource :report, :controller => 'reports', :only => [:show]
    end
    resources :time_entries, :controller => 'timelog'

    resources :wiki, :except => [:index, :new, :create] do
      collection do
        get :export
        get :date_index
        get '/index' => 'wiki#index'
      end

      member do
        get '/diff/:version/vs/:version_from' => 'wiki#diff', :as => 'wiki_diff'
        get '/diff(/:version)' => 'wiki#diff', :as => 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', :as => 'wiki_annotate'
        match :rename, :via => [:get, :put]
        get :parent_page, :action => 'edit_parent_page'
        put :parent_page, :action => 'update_parent_page'
        get :history
        post :protect
        post :add_attachment
        get  :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
        post :preview
      end
    end
    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => "wiki#show"

    namespace :work_packages do
      resources :calendar, :controller => 'calendars', :only => [:index]
    end

    resources :work_packages, :only => [:new, :create, :index] do
      get :new_type, :on => :collection

      collection do

app/controllers/work_packages/auto_completes_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

require 'rack/utils'

class WorkPackages::AutoCompletesController < ApplicationController
  before_filter :find_project

  def index
    @work_packages = []
    q = params[:q].to_s

    if q.present?
      query = (params[:scope] == "all" && Setting.cross_project_work_package_relations?) ? WorkPackage : @project.work_packages

      @work_packages |= query.visible.find_all_by_id(q.to_i) if q =~ /\A\d+\z/

      @work_packages |= query.visible.find(:all,
                                           limit: 10,
                                           order: "#{WorkPackage.table_name}.id ASC",
                                           conditions: ["LOWER(#{WorkPackage.table_name}.subject) LIKE :q OR CAST(#{WorkPackage.table_name}.id AS CHAR(13)) LIKE :q", {q: "%#{q.downcase}%" }])
    end

    respond_to do |format|
      format.html { render layout: false }
      format.any(:xml, :json) { render request.format.to_sym => wp_hash_with_string }
    end
  end

  private

  def wp_hash_with_string
    @work_packages.map do |wp|
      Hash[ wp.attributes.map do |key,value|
        [ key, Rack::Utils.escape_html(value) ]
      end << ['to_s', Rack::Utils.escape_html(wp.to_s)] ]
    end
  end

  def find_project
    project_id = (params[:work_package] && params[:work_package][:project_id]) || params[:project_id]
    @project = Project.find(project_id)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/controllers/work_packages/bulk_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class WorkPackages::BulkController < ApplicationController
  before_filter :disable_api
  before_filter :find_work_packages
  before_filter :authorize

  include JournalsHelper
  include ProjectsHelper
  include CustomFieldsHelper
  include RelationsHelper
  include QueriesHelper
  include IssuesHelper

  def edit
    @work_packages.sort!
    @available_statuses = @projects.map{|p|Workflow.available_statuses(p)}.inject{|memo,w|memo & w}
    @custom_fields = @projects.map{|p|p.all_work_package_custom_fields}.inject{|memo,c|memo & c}
    @assignables = @projects.map(&:possible_assignees).inject{|memo,a| memo & a}
    @responsibles = @projects.map(&:possible_responsibles).inject{|memo,a| memo & a}
    @types = @projects.map(&:types).inject{|memo,t| memo & t}
  end

  def update
    @work_packages.sort!

    unsaved_work_package_ids = []

    @work_packages.each do |work_package|
      work_package.reload
      work_package.add_journal(User.current, params[:notes])

      # filter parameters by whitelist and add defaults
      attributes = parse_params_for_bulk_work_package_attributes params, work_package.project
      work_package.assign_attributes attributes

      call_hook(:controller_work_package_bulk_before_save, { params: params, work_package: work_package })
      JournalObserver.instance.send_notification = params[:send_notification] == '0' ? false : true
      unless work_package.save
        unsaved_work_package_ids << work_package.id
      end
    end
    set_flash_from_bulk_save(@work_packages, unsaved_work_package_ids)
    redirect_back_or_default({controller: '/work_packages', action: :index, project_id: @project}, false)
  end

  def destroy
    unless WorkPackage.cleanup_associated_before_destructing_if_required(@work_packages, current_user, params[:to_do])

      respond_to do |format|
        format.html { render :locals => { work_packages: @work_packages,
                                          associated: WorkPackage.associated_classes_to_address_before_destruction_of(@work_packages) }
                    }
      end

    else

      destroy_work_packages(@work_packages)

      respond_to do |format|
        format.html { redirect_back_or_default(project_work_packages_path(@work_packages.first.project)) }
      end
    end
  end

private

  def destroy_work_packages(work_packages)
    work_packages.each do |work_package|
      begin
        work_package.reload.destroy
      rescue ::ActiveRecord::RecordNotFound
        # raised by #reload if work package no longer exists
        # nothing to do, work package was already deleted (eg. by a parent)
      end
    end
  end

  def parse_params_for_bulk_work_package_attributes(params, project)
    return {} unless params.has_key? :work_package

    safe_params = permitted_params.update_work_package project: project
    attributes = safe_params.reject {|k,v| v.blank?}
    attributes.keys.each {|k| attributes[k] = '' if attributes[k] == 'none'}
    attributes[:custom_field_values].reject! {|k,v| v.blank?} if attributes[:custom_field_values]
    attributes.delete :custom_field_values if not attributes.has_key?(:custom_field_values) or attributes[:custom_field_values].empty?
    attributes
  end

  # Sets the `flash` notice or error based the number of work packages that did not save
  #
  # @param [Array, WorkPackage] work_packages all of the saved and unsaved WorkPackages
  # @param [Array, Integer] unsaved_work_package_ids the WorkPackage ids that were not saved
  def set_flash_from_bulk_save(work_packages, unsaved_work_package_ids)
    if unsaved_work_package_ids.empty?
      flash[:notice] = l(:notice_successful_update) unless work_packages.empty?
    else
      flash[:error] = l(:notice_failed_to_save_work_packages,
                        :count => unsaved_work_package_ids.size,
                        :total => work_packages.size,
                        :ids => '#' + unsaved_work_package_ids.join(', #'))
    end
  end

  def default_breadcrumb
    l(:label_work_package_plural)
  end
end

app/views/work_packages/_action_menu.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% content_for :action_menu_specific do %>
  <%= li_unless_nil(link_to_if_authorized(l(:button_update), { :controller => '/work_packages',
                                                               :action => 'edit',
                                                               :id => work_package.id },
                                                               :class => 'edit icon icon-edit',
                                                               :accesskey => accesskey(:edit))) %>

  <%= li_unless_nil(watcher_link(work_package,
                                 User.current,
                                 { :class => 'watcher_link',
                                   :replace => User.current.allowed_to?(:view_work_package_watchers, @project) ? ['#watchers', '.watcher_link'] : ['.watcher_link'] })) %>
<% end %>
<% content_for :action_menu_more do %>
  <%= li_unless_nil(link_to_if_authorized l(:button_log_time), {:controller => '/timelog', :action => 'new', :work_package_id => controller.work_package}, :class => 'icon-context icon-time') %>
  <%= li_unless_nil(link_to_if_authorized l(:button_duplicate), {:controller => '/work_packages', :action => 'new', :project_id => @project, :copy_from => work_package }, :class => 'icon-context icon-duplicate') %>
  <%= li_unless_nil(link_to_if_authorized l(:button_copy), {:controller => '/work_packages/moves', :action => 'new', :work_package_id => controller.work_package, :copy => ''}, :class => 'icon-context icon-copy') %>
  <%= li_unless_nil(link_to_if_authorized l(:button_move), {:controller => '/work_packages/moves', :action => 'new', :work_package_id => controller.work_package}, :class => 'icon-context icon-move') %>

  <%= li_unless_nil(link_to_if_authorized l(:button_delete),
                                          { :controller => '/work_packages/bulk',
                                            :action => 'destroy',
                                            :ids => [work_package.id] },
                                          :confirm => (controller.work_package.leaf? ? l(:text_are_you_sure) : l(:text_are_you_sure_with_children)),
                                          :method => :delete ,
                                          :class => 'icon-context icon-delete' ) %>

  <%= call_hook(:view_work_package_show_action_menu, :work_package => controller.work_package) %>
<% end %>

app/views/work_packages/_changesets.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% changesets.each do |changeset| %>
    <div class="changeset <%= cycle('odd', 'even') %>">
    <p><%= link_to_revision(changeset, changeset.project,
                            :text => "#{l(:label_revision)} #{changeset.format_identifier}") %><br />
        <span class="author"><%= authoring(changeset.committed_on, changeset.author) %></span></p>
    <div class="wiki">
        <%= textilizable(changeset, :comments) %>
    </div>
    </div>
<% end %>

app/views/work_packages/_form.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= call_hook(:view_work_packages_form_details_top, { :issue => work_package, :form => f }) %>

<div id="work_package_descr_fields"<% unless work_package.new_record? || work_package.errors.any? %> style="display:none;"<% end %>>

  <% work_package_form_top_attributes(f, work_package,
                                         :priorities => priorities,
                                         :project => project).each do |attribute| %>
    <div class="attribute_wrapper">
      <%= attribute.field %>
    </div>

  <% end %>

</div>

<div id="attributes" class="attributes">
  <%= render :partial => 'attributes', :locals => { :f => f,
                                                    :work_package => work_package,
                                                    :project => project,
                                                    :priorities => priorities,
                                                    :user => user
                                                  } %>
</div>

<% if work_package.new_record? %>
  <hr class="form_separator" />
  <div class="handle_attachments">
    <%= label_tag('attachments[1][file]', l(:label_attachment_plural))%>
    <%= render :partial => 'attachments/form' %>
  </div>
<% end %>

<% if work_package.new_record? && User.current.allowed_to?(:add_work_package_watchers, project) -%>
  <hr class="form_separator" />
  <div id="watchers_form">
    <label class="watcher_label"><%= l(:label_work_package_watchers) %></label>
    <% work_package.project.users.sort.each do |user| -%>
      <label class="floating"><%= check_box_tag 'work_package[watcher_user_ids][]', user.id, work_package.watched_by?(user) %> <%=h user %></label>
    <% end -%>
  </div>
<% end %>

<%= call_hook(:view_work_packages_form_details_bottom, { :issue => work_package, :form => f }) %>

<%= wikitoolbar_for 'work_package_description' %>

app/views/work_packages/index.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= include_gon %>


<% breadcrumb_paths(l(:label_work_package_plural)) %>
<% if !query.new_record? && query.editable_by?(User.current) %>
  <% content_for :action_menu_specific do %>
    <%= li_unless_nil link_to(l(:button_edit), {:controller => '/queries', :action => 'edit', :id => query}, :class => 'icon icon-edit') %>
    <%= li_unless_nil link_to(l(:button_delete), {:controller => '/queries', :action => 'destroy', :id => query}, :confirm => l(:text_are_you_sure), :method => :post, :class => 'icon icon-delete') %>
  <% end %>
  <% unless project.nil? %>
    <% content_for :action_menu_more do %>
      <% if query.is_public? ? (current_user.allowed_to?(:manage_public_queries, project) || current_user.admin?) : current_user.allowed_to?(:save_queries, project, :global => true) %>
        <% if query_menu_item = query.query_menu_item %>
          <%= li_unless_nil link_to(l(:button_configure_menu_entry),edit_query_menu_item_path(project, query, query_menu_item)) %>
          <%= li_unless_nil link_to(l(:button_delete_menu_entry), query_menu_item_path(project, query, query_menu_item), :method => :delete) %>
        <% else %>
          <%= li_unless_nil(link_to(l(:button_add_menu_entry), query_menu_items_path(project, query), :method => :create)) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<h2><%= query.new_record? ? l(:label_work_package_plural) : h(query.name) %></h2>

<%= render :partial => 'layouts/action_menu_specific' %>

<div id="work-packages-index" ng-controller="WorkPackagesController">
  <div class="title-bar">
    <div class="title-bar-extras">

      <%= error_messages_for 'query' %>


      <% html_title(query.new_record? ? l(:label_work_package_plural) : h(query.name)) %>

      <% if visible_queries.any? %>
        <div id='work-packages-query-selection'>
          <%= label_tag 'query-select', l('apply_filter', :scope => 'queries') %>

          <%= select :query, :id, grouped_options_for_select(grouped_query_options, query.id), {:include_blank => query.new_record?, :selected => query.id}, {:id => 'query-select'} %>

        </div>
      <% end %>

      <%= render partial: 'query_form', locals: { project: project, query: query } %>


    </div><!-- .title-bar-extras -->
  </div><!-- .title-bar -->

  <% if query.valid? %>
    <%= render :partial => 'work_packages/list', :locals => { :query => query } %>

    <%= other_formats_links do |f| %>
      <%= f.link_to 'Atom', :url => { :project_id => project, :query_id => (query.new_record? ? nil : query), :key => User.current.rss_key } %>
      <%= f.link_to 'CSV', :url => { :project_id => project } %>
      <%= f.link_to 'PDF', :url => { :project_id => project } %>
      <%= f.link_to I18n.t(:label_pdf_with_descriptions), :url => { :project_id => project,
                                                                    :show_descriptions => true,
                                                                    :format => 'pdf' } %>
      <%= call_hook(:view_work_packages_index_other_formats, :link_formatter => f, :project => project) %>
    <% end if User.current.allowed_to? :export_work_packages, project, :global => project.nil? %>
  <% end %>
</div>

<%= call_hook(:view_work_packages_index_bottom, { :project => project, :query => query }) %>

<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>

<% content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom, {:query_id => query, :format => 'atom', :page => nil, :key => User.current.rss_key}, :title => l(:label_work_package_plural)) %>
  <%= auto_discovery_link_tag(:atom, {:controller => '/journals', :action => 'index', :query_id => query, :format => 'atom', :page => nil, :key => User.current.rss_key}, :title => l(:label_changes_details)) %>
<% end %>

<%= context_menu work_packages_context_menu_path %>